#!/bin/bash

function ReadUrlParam {  
 saveIFS=$IFS
  IFS='=&'
  parm=($QUERY_STRING)
  IFS=$saveIFS
  for ((i=0; i<${#parm[@]}; i+=2))
  do
      URLParam[${parm[i]}]=${parm[i+1]}
  done
}


TDIR="/usr/www"
UDIR="/usr/openkarotz"
SURL="http://karotz.filippi.org/2.0"
IP=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`

ReadUrlParam

if [ -f "$TDIR/ok.version" ]; then
   echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
   echo "Connection: close"
   echo "Accept-Ranges: bytes"
   echo "Content-type: text/plain"
   echo ""
   
   echo 'Open Karotz Allready Installed'
   echo 'Use http://'${IP}' to go to main page'
else
    killall immortaldog >>/dev/null 2>>/dev/null
    mkdir /usr/www >>/dev/null 2>>/dev/null
    mkdir /usr/www/cgi-bin >>/dev/null 2>>/dev/null

    mkdir /usr/openkarotz >>/dev/null 2>>/dev/null
    wget $SURL/setup.inc.karotz -q -O /usr/www/cgi-bin/setup.inc
    chmod 777 /usr/www/cgi-bin/setup.inc

    wget $SURL/install -q -O /tmp/install
    chmod 777 /tmp/install >>/dev/null 2>>/dev/null
    bash /tmp/install 1 1  >>/dev/null 2>>/dev/null
fi

echo ''
echo 'Use http://'${IP}' to go to main page'

